"""Guard the migration's security invariants with a cheap check.

These are not style assertions. Each one catches a specific regression that would otherwise ship
silently: a new table that forgets FORCE RLS, a team-scoped table without a scope column, or a
migration that stops being re-runnable.

The RLS policy statements for looped tables are generated by `format()` inside the DO block, so
these tests assert on the *declared arrays* and on the tables the loop actually reaches, not on
literal SQL text. Asserting on text would pass while the loop silently skipped a table.
"""

from __future__ import annotations

import pathlib
import re

MIGRATION = pathlib.Path(__file__).resolve().parents[1] / "supabase" / "migrations" / "001_core.sql"
SQL = MIGRATION.read_text(encoding="utf-8")

EXPECTED_TABLES = {
    "organizations", "teams", "departments", "people", "org_roles", "slack_links",
    "tasks", "task_transitions", "policies", "agent_runs", "audit_logs",
}
# Tables whose rows a team lead must not be able to read across teams.
TEAM_SCOPED = {"departments", "people", "slack_links", "tasks", "agent_runs"}


def _created_tables() -> set[str]:
    return set(re.findall(r"CREATE TABLE IF NOT EXISTS public\.(\w+)", SQL))


def _loop_array(name: str) -> set[str]:
    match = re.search(rf"{name}\s+text\[\]\s*:=\s*ARRAY\[(.*?)\];", SQL, re.DOTALL)
    assert match, f"{name} array not found in the policy DO block"
    return set(re.findall(r"'(\w+)'", match.group(1)))


def _table_body(table: str) -> str:
    match = re.search(rf"CREATE TABLE IF NOT EXISTS public\.{table} \((.*?)\n\);", SQL, re.DOTALL)
    assert match, f"{table} definition not found"
    return match.group(1)


def test_all_expected_tables_exist():
    assert _created_tables() == EXPECTED_TABLES


def test_every_team_scoped_table_declares_the_scope_columns():
    """The visibility predicate takes (org_id, team_id); a table missing either cannot use it.

    This test exists because `teams` and `slack_links` originally shipped without `team_id` and
    the policy would not have compiled. `teams` is the deliberate exception: it *is* the scope,
    so its policy passes `id` as the team argument.
    """
    for table in TEAM_SCOPED:
        body = _table_body(table)
        assert "org_id" in body, f"{table} has no org_id"
        assert "team_id" in body, f"{table} has no team_id scope"
    assert "id" in _table_body("teams")
    assert "team_id" not in _table_body("teams")


def test_policy_loops_cover_every_table_exactly_once():
    """A table missing from every array would ship with no RLS at all."""
    handled = _loop_array("team_scoped") | _loop_array("org_scoped") | {
        "teams",  # explicit block: scoped by its own id
        "organizations",  # explicit block: scoped by its own id
        "org_roles",  # explicit block: read and write have different scopes
        "task_transitions",  # explicit block: reference table, no tenant data
    }
    assert handled == _created_tables()


def test_reference_table_has_no_rls_but_no_anon_access():
    """`task_transitions` is the state machine itself: no org_id, no tenant data, so no RLS.

    It must still be closed to `anon`, because the default grant would otherwise publish the
    whole transition graph to any unauthenticated browser.
    """
    do_block = SQL[SQL.index("DO $$") :]
    assert "REVOKE ALL ON public.task_transitions FROM anon" in do_block
    assert "ALTER TABLE public.task_transitions ENABLE ROW LEVEL SECURITY" not in do_block


def test_teams_policy_uses_its_own_id_as_scope():
    """Regression guard for the bug above: `row_visible(org_id, team_id)` on a table with no
    team_id column does not compile."""
    teams_policy = re.search(
        r"CREATE POLICY tenant_isolation ON public\.teams(.*?);", SQL, re.DOTALL
    )
    assert teams_policy, "teams policy not found"
    assert "app_private.row_visible(org_id, id))" in SQL
    assert "row_visible(org_id, team_id))" not in teams_policy.group(1)


def test_rls_and_grants_reach_every_table():
    """ENABLE without FORCE lets the table owner bypass the policy — and the app IS the owner.

    Three coverage paths, and every table must be in exactly one of them:
      * the two loops, which apply their statements via format('%I') to each member;
      * explicit blocks for tables whose scope argument is not a column (`teams`,
        `organizations`);
      * `task_transitions`, a reference table with no tenant data and therefore no RLS.
    """
    do_block = SQL[SQL.index("DO $$") :]

    for statement in (
        "ENABLE ROW LEVEL SECURITY",
        "FORCE ROW LEVEL SECURITY",
        "REVOKE ALL ON public.%I FROM anon",
        "GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated",
    ):
        assert statement in do_block, f"loop is missing: {statement}"

    for table in ("teams", "organizations"):
        assert f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY" in do_block, table
        assert f"ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY" in do_block, table
        assert f"REVOKE ALL ON public.{table} FROM anon" in do_block, table

    # The reference table must be closed to anon without being given RLS it does not need.
    assert "REVOKE ALL ON public.task_transitions FROM anon" in do_block


def test_visibility_predicate_is_fail_closed():
    """No tenant setting set must yield zero rows, never all rows.

    `p_org_id IS NOT NULL` plus equality is the whole guarantee; a bare NULL comparison would
    evaluate to NULL and quietly leak.
    """
    assert "p_org_id IS NOT NULL" in SQL
    assert "p_org_id = app_private.current_org_id()" in SQL


def test_row_visible_has_exactly_three_clauses():
    """A lead must not reach another team, so the predicate may widen scope exactly twice:
    org-level rows (team_id NULL) and the owner. A third alternative is a leak waiting to happen.
    """
    body_match = re.search(r"FUNCTION app_private\.row_visible\(.*?\$\$;", SQL, re.DOTALL)
    assert body_match, "row_visible definition not found"
    body = body_match.group(0)
    assert body.count("OR") == 2, body
    assert "app_private.is_ceo()" in body
    assert "p_team_id = app_private.current_team_id()" in body


def test_migration_is_rerunnable():
    """app/db.py applies this on every boot, so re-running must be safe."""
    assert "CREATE TABLE IF NOT EXISTS" in SQL
    assert "CREATE INDEX IF NOT EXISTS" in SQL
    assert "CREATE OR REPLACE FUNCTION" in SQL
    assert "DROP TRIGGER IF EXISTS" in SQL
    assert "ON CONFLICT DO NOTHING" in SQL
    # CREATE TYPE has no IF NOT EXISTS in Postgres, so an enum would break every re-run.
    assert not re.search(r"^\s*CREATE TYPE\b", SQL, re.MULTILINE)


def test_rls_helpers_are_defined_after_what_they_read():
    """`LANGUAGE sql` bodies are validated at creation, so ordering is correctness, not style."""
    org_roles = SQL.index("CREATE TABLE IF NOT EXISTS public.org_roles")
    is_ceo = SQL.index("FUNCTION app_private.is_ceo()")
    current_team = SQL.index("FUNCTION app_private.current_team_id()")
    visible = SQL.index("FUNCTION app_private.row_visible")
    assert org_roles < is_ceo
    assert current_team < visible
    assert is_ceo < visible


def test_task_state_machine_lives_in_the_database():
    assert "CREATE TABLE IF NOT EXISTS public.task_transitions" in SQL
    assert "FROM public.task_transitions" in SQL  # the trigger actually reads it
    assert "invalid task transition" in SQL
    assert "stale task version" in SQL  # optimistic concurrency


def test_runaway_delegation_is_constrained_in_the_schema():
    """An unbounded delegation loop is the number one runaway cost, so it is a CHECK."""
    assert "delegations         integer NOT NULL DEFAULT 0 CHECK (delegations <= 3)" in SQL
    assert "handoffs            integer NOT NULL DEFAULT 0 CHECK (handoffs <= 5)" in SQL


def test_idempotency_key_is_unique_per_org():
    """A repeated Slack webhook must not create a second task, nor re-bill the owner."""
    assert "UNIQUE (org_id, idempotency_key)" in SQL


def test_cost_evidence_columns_exist():
    """Degradation and cost claims are impossible without these being recorded per run."""
    for column in ("cached_tokens", "cache_creation_tokens", "cost_brl", "retry_count",
                   "format_violation", "latency_ms"):
        assert column in SQL, column


def test_audit_log_is_append_only():
    assert "REVOKE UPDATE, DELETE ON public.audit_logs" in SQL


def test_service_role_has_table_grants():
    """BYPASSRLS skips the policy check, NOT the grant check: without GRANTs, every server-side
    write fails with plain "permission denied" — including the orchestrator's own.
    """
    assert "GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role" in SQL


def test_schema_usage_is_granted_but_create_is_not():
    """PostgREST resolves table names through the schema (needs USAGE); USAGE-without-CREATE is
    the shape that keeps a compromised tenant credential from creating objects.
    """
    assert "GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role, authenticator" in SQL
    assert "GRANT CREATE ON SCHEMA public" not in SQL


def test_policy_helpers_are_callable_by_every_querying_role():
    """RLS policy expressions execute as the querying role — including `anon` for unauthenticated
    PostgREST requests. Without USAGE here, anonymous reads fail AFTER the JWT validated, which
    looks exactly like a broken key. This exact line was the bug; the test pins it.
    """
    assert "GRANT USAGE ON SCHEMA app_private TO anon, authenticated, service_role" in SQL


def test_anon_role_is_denied_everywhere():
    """The unauthenticated Postgres role must not read tenant data even if PostgREST is sloppy.

    Looped tables are revoked by the loop, the three explicit ones by name. Both paths are
    asserted: checking only the loop would pass while a table sat outside it.
    """
    do_block = SQL[SQL.index("DO $$") :]
    assert "REVOKE ALL ON public.%I FROM anon" in do_block  # the loop
    for table in _created_tables() - (_loop_array("team_scoped") | _loop_array("org_scoped")):
        assert f"REVOKE ALL ON public.{table} FROM anon" in do_block, table


def test_only_ceo_holds_approval_authority():
    """team_lead is consultive by decision; the schema must not imply otherwise."""
    assert "'ceo','team_lead','member','viewer'" in SQL
    # No approval_limit table exists yet: with a consultive lead it has no consumer, and
    # speculative columns are how a product grows a permissions model nobody tested.
    assert not re.search(r"CREATE TABLE IF NOT EXISTS public\.approval_limit", SQL)
